alter table if exists authorities drop foreign key if exists FKhjuy9y4fd8v5m3klig05ktofg;
alter table if exists character_episode drop foreign key if exists FKm6hmio03dhcqs9vkvfm76f3vf;
alter table if exists character_episode drop foreign key if exists FKr6idg38482wdp7n8jxesptqyu;
alter table if exists characters drop foreign key if exists FK92utx2lllqdkqalurreq5h43r;
alter table if exists characters drop foreign key if exists FKd3pgsseclg08j4x78hvt0yf1n;
alter table if exists user_favorites drop foreign key if exists FK91hvh1gui6m5qt5agtmo8ojks;
drop table if exists authorities;
drop table if exists character_episode;
drop table if exists characters;
drop table if exists episodes;
drop table if exists locations;
drop table if exists user_favorites;
drop table if exists users;

create table authorities (id bigint not null auto_increment, authority varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table character_episode (character_id integer not null, episode_id integer not null, primary key (character_id, episode_id)) engine=InnoDB;
create table characters (id integer not null auto_increment, location_id integer not null, origin_id integer not null, source_id integer not null, created datetime(6) not null, gender varchar(255) not null, image varchar(255) not null, name varchar(255) not null, species varchar(255) not null, status varchar(255) not null, type varchar(255), primary key (id)) engine=InnoDB;
create table episodes (id integer not null auto_increment, source_id integer not null, created datetime(6), air_date varchar(255) not null, episode varchar(255) not null, name varchar(255) not null, primary key (id)) engine=InnoDB;
create table locations (id integer not null auto_increment, source_id integer not null, created datetime(6) not null, dimension varchar(255) not null, name varchar(255) not null, type varchar(255) not null, primary key (id)) engine=InnoDB;
create table user_favorites (character_id integer, id integer not null auto_increment, username varchar(255), primary key (id)) engine=InnoDB;
create table users (enabled bit not null, password varchar(255) not null, username varchar(255) not null, primary key (username)) engine=InnoDB;
alter table if exists character_episode add constraint UK63kur5052ug64m0t8saek4co8 unique (character_id);
alter table if exists character_episode add constraint UKljhddgorg1lxxq1gpwpfq9cgf unique (episode_id);
alter table if exists characters add constraint UK2cdrn845gk3iddssbdvh797sr unique (source_id);
alter table if exists episodes add constraint UKddkles17asmedse8c95uwsn31 unique (source_id);
alter table if exists episodes add constraint UKl9vh14ovyme2n3w8pc3nsm68t unique (name);
alter table if exists locations add constraint UK4wah46qtfam5dxp2qvei6brr3 unique (source_id);
alter table if exists authorities add constraint FKhjuy9y4fd8v5m3klig05ktofg foreign key (username) references users (username);
alter table if exists character_episode add constraint FKm6hmio03dhcqs9vkvfm76f3vf foreign key (character_id) references characters (id);
alter table if exists character_episode add constraint FKr6idg38482wdp7n8jxesptqyu foreign key (episode_id) references episodes (id);
alter table if exists characters add constraint FK92utx2lllqdkqalurreq5h43r foreign key (location_id) references locations (id);
alter table if exists characters add constraint FKd3pgsseclg08j4x78hvt0yf1n foreign key (origin_id) references locations (id);
alter table if exists user_favorites add constraint FK91hvh1gui6m5qt5agtmo8ojks foreign key (character_id) references characters (id);
